name: Mirror ELK Images

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Какой образ зеркалим? (например: filebeat)'
        required: true
        default: 'filebeat'
      image_tag:
        description: 'Тег образа (например: 8.19.10)'
        required: true
        default: '8.19.10'

permissions:
  contents: read
  packages: write

jobs:
  push_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }} 

      - name: Pull, Tag and Push
        run: |
          IMAGE_NAME="${{ github.event.inputs.image_name }}"
          IMAGE_TAG="${{ github.event.inputs.image_tag }}"
          
          # Логика для разных путей Elastic
          if [[ "$IMAGE_NAME" == "filebeat" || "$IMAGE_NAME" == "metricbeat" ]]; then
            SOURCE="docker.elastic.co/beats/$IMAGE_NAME:$IMAGE_TAG"
          else
            # Для elasticsearch, kibana, logstash путь обычно плоский
            SOURCE="docker.elastic.co/$IMAGE_NAME/$IMAGE_NAME:$IMAGE_TAG"
          fi
          
          TARGET="ghcr.io/${{ github.actor }}/$IMAGE_NAME:$IMAGE_TAG"
          
          # 2. Выполняем перенос
          echo "Mirroring $SOURCE to $TARGET..."
          docker pull $SOURCE
          docker tag $SOURCE $TARGET
          docker push $TARGETname: 
