name: Mirror ELK Images

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  push_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Mirror Elasticsearch
        run: |
          docker pull docker.elastic.co/elasticsearch/elasticsearch:8.19.10
          docker tag docker.elastic.co/elasticsearch/elasticsearch:8.19.10 ghcr.io/leshevi/elasticsearch:8.19.10
          docker push ghcr.io/leshevi/elasticsearch:8.19.10

      - name: Mirror Kibana
        run: |
          docker pull docker.elastic.co/kibana/kibana:8.19.10
          docker tag docker.elastic.co/kibana/kibana:8.19.10 ghcr.io/leshevi/kibana:8.19.10
          docker push ghcr.io/leshevi/kibana:8.19.10

      - name: Mirror Logstash
        run: |
          docker pull docker.elastic.co/logstash/logstash:8.19.10
          docker tag docker.elastic.co/logstash/logstash:8.19.10 ghcr.io/leshevi/logstash:8.19.10
          docker push ghcr.io/leshevi/logstash:8.19.10
