name: Mirror Images to GHCR

on:
  workflow_dispatch:
    inputs:
      source_image:
        description: 'postgres:17-alpine'
        required: true
      target_name:
        description: 'my-postgress'
        required: true

permissions:
  contents: read
  packages: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }} 

      - name: Pull, Tag and Push
        run: |
          USER_LOWER=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          SRC="${{ github.event.inputs.source_image }}"
          TGT="ghcr.io/${USER_LOWER}/${{ github.event.inputs.target_name }}:latest"

          echo "Mirroring $SRC to $TGT"
          
          docker pull "$SRC"
          docker tag "$SRC" "$TGT"
          docker push "$TGT"
